// ═══════════════════════════════════════════
// SHARING & DOCUMENTATION
// ═══════════════════════════════════════════

const _isWebMode = !window.electronAPI;

async function shareCollection(colId) {
  const col = findNodeInAll(colId);
  if (!col) return;

  const shareData = deepClone(col);

  if (_isWebMode) {
    try {
      const resp = await fetch(restifyApiUrl('/api/share/quick'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ collection: shareData, name: col.name })
      });
      if (!resp.ok) throw new Error('Server returned ' + resp.status);
      const result = await resp.json();
      showShareResult(result, col.name);
    } catch (err) {
      showNotif('Share failed: ' + err.message, 'error');
    }
  } else {
    generateShareableDocsHtml(col);
  }
}

function generateShareableDocsHtml(col) {
  const requests = [];
  function collect(node, path) {
    if (node.type === 'request') {
      requests.push({ method: node.method || 'GET', name: node.name || 'Untitled', url: node.url || '', path: path });
    }
    if (node.children) {
      node.children.forEach(c => collect(c, node.type === 'collection' ? '' : (path ? path + ' / ' + node.name : node.name)));
    }
  }
  collect(col, '');

  const methodColors = { GET: '#22c55e', POST: '#eab308', PUT: '#3b82f6', PATCH: '#a855f7', DELETE: '#ef4444', HEAD: '#06b6d4', OPTIONS: '#6b7280' };
  let rows = '';
  let currentPath = null;
  requests.forEach(r => {
    const folder = r.path || '(root)';
    if (folder !== currentPath) {
      currentPath = folder;
      if (r.path) rows += '<tr><td colspan="3" style="padding:16px 0 6px;font-weight:700;font-size:12px;text-transform:uppercase;letter-spacing:.5px;color:#888;border-bottom:1px solid #333">\u{1F4C1} ' + _escShareHtml(r.path) + '</td></tr>';
    }
    const mc = methodColors[r.method] || '#888';
    rows += '<tr style="border-bottom:1px solid #222"><td style="padding:8px 12px"><span style="background:' + mc + '22;color:' + mc + ';font-weight:700;font-size:11px;padding:2px 8px;border-radius:4px;font-family:monospace">' + _escShareHtml(r.method) + '</span></td><td style="padding:8px 12px;font-weight:500">' + _escShareHtml(r.name) + '</td><td style="padding:8px 12px;font-family:monospace;font-size:12px;color:#999">' + _escShareHtml(r.url) + '</td></tr>';
  });

  const desc = col.description ? '<p style="color:#aaa;line-height:1.6;margin:0 0 24px">' + _escShareHtml(col.description) + '</p>' : '';

  const html = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' + _escShareHtml(col.name) + ' — Restify API Docs</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#111;color:#eee;padding:40px 20px}table{width:100%;border-collapse:collapse}a{color:#ef5c35}</style></head><body><div style="max-width:900px;margin:0 auto"><div style="display:flex;align-items:center;gap:12px;margin-bottom:8px"><div style="width:40px;height:40px;background:#ef5c35;border-radius:10px;display:flex;align-items:center;justify-content:center;font-weight:900;color:#fff;font-size:18px">R</div><h1 style="font-size:24px;font-weight:700">' + _escShareHtml(col.name) + '</h1></div><p style="font-size:13px;color:#666;margin-bottom:20px">' + requests.length + ' requests · Generated by <a href="https://restify.online/" target="_blank" rel="noopener">Restify</a></p>' + desc + '<table>' + rows + '</table><div style="margin-top:40px;padding-top:16px;border-top:1px solid #222;font-size:11px;color:#555;text-align:center">Exported from Restify</div></div></body></html>';

  const blob = new Blob([html], { type: 'text/html' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = (col.name || 'collection').replace(/[^a-zA-Z0-9_-]/g, '_') + '-docs.html';
  a.click();
  URL.revokeObjectURL(a.href);
  showNotif('Documentation HTML downloaded — share the file or host it anywhere', 'success');
}

function _escShareHtml(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function showShareResult(result, name) {
  document.getElementById('shareCollectionName').textContent = name;
  document.getElementById('shareDocUrl').value = result.docUrl;
  document.getElementById('shareImportUrl').value = result.importUrl;
  document.getElementById('shareDocLink').href = result.docUrl;
  document.getElementById('shareModal').classList.add('open');
}

function closeShareModal() {
  document.getElementById('shareModal').classList.remove('open');
}

function copyShareUrl(inputId) {
  const input = document.getElementById(inputId);
  navigator.clipboard.writeText(input.value).then(() => showNotif('Link copied!', 'success'));
}

async function checkAutoImport() {
  const params = new URLSearchParams(window.location.search);
  const importId = params.get('import');
  if (!importId) return;

  try {
    const resp = await fetch(restifyApiUrl(`/api/shared/${importId}`));
    if (!resp.ok) throw new Error('Collection not found');
    const data = await resp.json();

    if (data.collection) {
      const col = data.collection;
      assignNewIds(col);
      collections.push(col);
      openFolders.add(col.id);
      saveState();
      renderSidebar();
      showNotif(`Imported "${col.name}"`, 'success');
      window.history.replaceState({}, '', '/');
    }
  } catch (err) {
    showNotif('Import failed: ' + err.message, 'error');
  }
}
